### ISSUE TITLE
When to release code?

### ISSUE THREAD

**Issue by silence-tang** [johnberg1/CLIPInverter#1]
Great work! May I ask when do you plan to release code?

**Comment by junyizeng** [comment]
+1

**Comment by johnberg1** [comment]
Hi, thank you very much for your interest in our work! I am working on cleaning the repository and I will be sharing the code as soon as possible. Sorry about the delay. Meanwhile, you can access the inference code and the pretrained models from our huggingface repository here: https://huggingface.co/spaces/johnberg/CLIPInverter/tree/main

I will update this issue as soon as I release the code.

**Comment by silence-tang** [comment]
Thanks very much! May I ask what's the inference time? Is it fast to edit an input image？

**Comment by johnberg1** [comment]
Yes, editing is just a forward pass through our model, so it should take less than a second on a GPU. Our huggingface demo does not have GPU support yet, it runs on a CPU. Therefore it takes around 10-15 seconds to edit each image.

**Comment by silence-tang** [comment]
Ok, I know. Thank you!

**Comment by johnberg1** [comment]
The training code is released now.
